"""followers

Revision ID: 642a16b6a8fb
Revises: e047c9bd6b29
Create Date: 2026-06-28 10:59:18.522756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642a16b6a8fb'
down_revision = 'e047c9bd6b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
